name = "Hugo Clean Blog"
license = "MIT"
licenselink = "https://github.com/go-zen-chu/hugo-clean-blog-theme/blob/master/LICENSE.md"
description = "Hugo Clean Blog Theme"
homepage = "https://github.com/go-zen-chu/hugo-clean-blog-theme"
tags = ["blog", "bootstrap"]
features = ["blog", "bootstrap"]
min_version = 0.17

[author]
  name = "Akira Masuda"
  homepage = "https://amasuda.xyz"

# original theme
[original]
  name = "Startbootstrap Clean Blog"
  homepage = "https://startbootstrap.com/previews/clean-blog"
  repo = "https://github.com/startbootstrap/startbootstrap-clean-blog"
